/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* The version of the OpenAPI document: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.m_burst.alfabattle.task1.providers.alfa.atm.model

import com.github.m_burst.alfabattle.task1.providers.alfa.atm.model.ATMAccess
import com.github.m_burst.alfabattle.task1.providers.alfa.atm.model.ATMServices
import com.github.m_burst.alfabattle.task1.providers.alfa.atm.model.Coordinates
import com.github.m_burst.alfabattle.task1.providers.alfa.atm.model.PostAddress
import com.github.m_burst.alfabattle.task1.providers.alfa.atm.model.SupportInfo

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * Статическая и редкоменяющаяся информация о банкомате
 * @param address 
 * @param addressComments Вспомогательный текстовый комментарий, помогающий пользователю найти АТМ. Например, «справа от входа в торговый комплекс с улицы Кораблестроителей»
 * @param availablePaymentSystems 
 * @param cashInCurrencies Список кодов валют по общероссийскому классификатору, которые АТМ поддерживает для внесения
 * @param cashOutCurrencies Список кодов валют по общероссийскому классификатору, которые АТМ поддерживает для выдачи
 * @param coordinates 
 * @param deviceId Номер Terminal-ID, присвоенный АТМ в процессинге Банка и передаваемый в информационном обмене между эквайрером, платежной системой и эмитентом.  Значение соответствует ISO-8583 полю 41 (Card Acceptor Terminal Identification)
 * @param nfc 
 * @param publicAccess Доступ к АТМ. Значения: 1 = в помещении кредитной организации в открытом доступе  2 = в помещении кредитной организации в ограниченном доступе  3 = вне помещения кредитной организации в открытом доступе  4 = вне помещения кредитной организации в ограниченном доступе  (значения соответствуют правилам заполнения Ф-250 ЦБ РФ1)  
 * @param recordUpdated Дата/время получения последней информации из master-системы
 * @param services 
 * @param supportInfo 
 * @param timeAccess 
 * @param timeShift Сдвиг времени региона установки конкретного АТМ, относительно UTC. Например, 3
 */

data class ATMDetails (
    @JsonProperty("address")
    val address: PostAddress? = null,
    /* Вспомогательный текстовый комментарий, помогающий пользователю найти АТМ. Например, «справа от входа в торговый комплекс с улицы Кораблестроителей» */
    @JsonProperty("addressComments")
    val addressComments: kotlin.String? = null,
    @JsonProperty("availablePaymentSystems")
    val availablePaymentSystems: kotlin.Array<kotlin.String>? = null,
    /* Список кодов валют по общероссийскому классификатору, которые АТМ поддерживает для внесения */
    @JsonProperty("cashInCurrencies")
    val cashInCurrencies: kotlin.Array<kotlin.String>? = null,
    /* Список кодов валют по общероссийскому классификатору, которые АТМ поддерживает для выдачи */
    @JsonProperty("cashOutCurrencies")
    val cashOutCurrencies: kotlin.Array<kotlin.String>? = null,
    @JsonProperty("coordinates")
    val coordinates: Coordinates? = null,
    /* Номер Terminal-ID, присвоенный АТМ в процессинге Банка и передаваемый в информационном обмене между эквайрером, платежной системой и эмитентом.  Значение соответствует ISO-8583 полю 41 (Card Acceptor Terminal Identification) */
    @JsonProperty("deviceId")
    val deviceId: kotlin.Int? = null,
    @JsonProperty("nfc")
    val nfc: kotlin.String? = null,
    /* Доступ к АТМ. Значения: 1 = в помещении кредитной организации в открытом доступе  2 = в помещении кредитной организации в ограниченном доступе  3 = вне помещения кредитной организации в открытом доступе  4 = вне помещения кредитной организации в ограниченном доступе  (значения соответствуют правилам заполнения Ф-250 ЦБ РФ1)   */
    @JsonProperty("publicAccess")
    val publicAccess: kotlin.String? = null,
    /* Дата/время получения последней информации из master-системы */
    @JsonProperty("recordUpdated")
    val recordUpdated: java.time.OffsetDateTime? = null,
    @JsonProperty("services")
    val services: ATMServices? = null,
    @JsonProperty("supportInfo")
    val supportInfo: SupportInfo? = null,
    @JsonProperty("timeAccess")
    val timeAccess: ATMAccess? = null,
    /* Сдвиг времени региона установки конкретного АТМ, относительно UTC. Например, 3 */
    @JsonProperty("timeShift")
    val timeShift: kotlin.Int? = null
)

