/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* The version of the OpenAPI document: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.m_burst.alfabattle.task1.providers.alfa.atm.model


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param cardCashIn Операции внесения наличных денежных средств с использованием платежных карт и их реквизитов
 * @param cardCashOut Операция выдачи наличных с использованием платежных карт и их реквизитов
 * @param cardPayments Платежи (оплата товаров и услуг) в пользу поставщиков услуг и третьих лиц с использованием платежных карт и их реквизитов
 * @param cashIn Операции внесения наличных денежных средств БЕЗ использования платежных карт и их реквизитов
 * @param cashOut Операция выдачи наличных БЕЗ использования платежных карт и их реквизитов
 * @param payments Платежи (Оплата товаров и услуг) в пользу поставщиков услуг и третьих лиц БЕЗ использования платежных карт и их реквизитов
 */

data class ATMServices (
    /* Операции внесения наличных денежных средств с использованием платежных карт и их реквизитов */
    @JsonProperty("cardCashIn")
    val cardCashIn: kotlin.String? = null,
    /* Операция выдачи наличных с использованием платежных карт и их реквизитов */
    @JsonProperty("cardCashOut")
    val cardCashOut: kotlin.String? = null,
    /* Платежи (оплата товаров и услуг) в пользу поставщиков услуг и третьих лиц с использованием платежных карт и их реквизитов */
    @JsonProperty("cardPayments")
    val cardPayments: kotlin.String? = null,
    /* Операции внесения наличных денежных средств БЕЗ использования платежных карт и их реквизитов */
    @JsonProperty("cashIn")
    val cashIn: kotlin.String? = null,
    /* Операция выдачи наличных БЕЗ использования платежных карт и их реквизитов */
    @JsonProperty("cashOut")
    val cashOut: kotlin.String? = null,
    /* Платежи (Оплата товаров и услуг) в пользу поставщиков услуг и третьих лиц БЕЗ использования платежных карт и их реквизитов */
    @JsonProperty("payments")
    val payments: kotlin.String? = null
)

