/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* The version of the OpenAPI document: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.m_burst.alfabattle.task1.providers.alfa.atm.model

import com.github.m_burst.alfabattle.task1.providers.alfa.atm.model.AvailableNow

import com.fasterxml.jackson.annotation.JsonProperty
/**
 * Информация по доступности функций АТМ
 * @param availableNow 
 * @param deviceId Номер Terminal-ID, присвоенный АТМ в процессинге Банка и передаваемый в информационном обмене между эквайрером, платежной системой и эмитентом.  Значение соответствует ISO-8583 полю 41 (Card Acceptor Terminal Identification)
 * @param recordUpdated Дата/время получения последней информации из master-системы
 */

data class ATMStatus (
    @JsonProperty("availableNow")
    val availableNow: AvailableNow? = null,
    /* Номер Terminal-ID, присвоенный АТМ в процессинге Банка и передаваемый в информационном обмене между эквайрером, платежной системой и эмитентом.  Значение соответствует ISO-8583 полю 41 (Card Acceptor Terminal Identification) */
    @JsonProperty("deviceId")
    val deviceId: kotlin.Int? = null,
    /* Дата/время получения последней информации из master-системы */
    @JsonProperty("recordUpdated")
    val recordUpdated: java.time.OffsetDateTime? = null
)

