/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* The version of the OpenAPI document: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.m_burst.alfabattle.task1.providers.alfa.atm.model


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param latitude Широта
 * @param longitude Долгота
 */

data class Coordinates (
    /* Широта */
    @JsonProperty("latitude")
    val latitude: kotlin.String? = null,
    /* Долгота */
    @JsonProperty("longitude")
    val longitude: kotlin.String? = null
)

