/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* The version of the OpenAPI document: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.m_burst.alfabattle.task1.providers.alfa.atm.model


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param code Код ошибки
 * @param message Сообщение об ошибке
 */

data class Error (
    /* Код ошибки */
    @JsonProperty("code")
    val code: kotlin.Int? = null,
    /* Сообщение об ошибке */
    @JsonProperty("message")
    val message: kotlin.String? = null
)

