/**
* Сервис проверки статуса банкоматов
* Сервис, возвращающий информацию о банкоматах Альфа-Банка
*
* The version of the OpenAPI document: 1.0.0
* Contact: apisupport@alfabank.ru
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.m_burst.alfabattle.task1.providers.alfa.atm.model


import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 * @param city 
 * @param location 
 * @param mode 
 */

data class PostAddress (
    @JsonProperty("city")
    val city: kotlin.String? = null,
    @JsonProperty("location")
    val location: kotlin.String? = null,
    @JsonProperty("mode")
    val mode: PostAddress.Mode? = null
) {

    /**
    * 
    * Values: FIAS,KLADR,OTHER_DICTIONARY,HAND_MADE
    */
    
    enum class Mode(val value: kotlin.String){
        @JsonProperty(value="FIAS") FIAS("FIAS"),
        @JsonProperty(value="KLADR") KLADR("KLADR"),
        @JsonProperty(value="OtherDictionary") OTHER_DICTIONARY("OtherDictionary"),
        @JsonProperty(value="HandMade") HAND_MADE("HandMade");
    }
}

